### ISSUE TITLE
Risk under WCAG Success Criterion 1.4.4: Resize Text

### ISSUE THREAD

**Issue by aardrian** [Typetura/Typetura#44] opened 2021-04-05 22:36 UTC
I need to give some context for the issue first…

Under the Web Content Accessibility Guidelines 2.x, [Success Criterion 1.4.4: Resize Text (Level AA)](https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=144#resize-text) has the following language:

> Except for captions and images of text, text can be resized without assistive technology up to 200 percent without loss of content or functionality.

The [Understanding](https://www.w3.org/WAI/WCAG21/Understanding/resize-text.html) document gives some more detail:

> Content satisfies the Success Criterion if it can be scaled up to 200%, that is, up to twice the width and height.

Using the browser zoom feature is generally considered to be the standard method to allow a user to zoom the text of the page (by zooming the page overall). Responsive design has made this effective.

As I do accessibility reviews, where WCAG compliance is the objective, I am running into cases where CSS is used to limit how large text can get. Sometimes it is because of reliance on viewport units in CSS ([called out explicitly as a likely failure](https://www.w3.org/WAI/WCAG21/Techniques/failures/F94.html) in WCAG), sometimes it is because of combinations of `calc()`, `clamp()`, or `max()` (which I demonstrate in my 2019 post, [_Responsive Type and Zoom_](https://adrianroselli.com/2019/12/responsive-type-and-zoom.html)).

I have lately encountered sites that use Typetura and have found they do not pass this WCAG SC because the text cannot be scaled to 200%.

The problem here is that I cannot share these sites because clients. However, I saw this [_Intrinsic Typography demo with Typetura_](https://codepen.io/scottkellum/pen/poNXLYV) shared via Codepen and found it demonstrates the issue pretty well, right up to the 200% number (my client sites do not suddenly self-correct at 200%, however).

Using the [debug mode of the pen](https://cdpn.io/scottkellum/debug/poNXLYV) removes the Codepen wrapper so I can demonstrate the effect more easily.

The following screen shots are Chrome 89 with no plug-ins on Windows running at 3,000 × 1,920.

![typetura-100](https://user-images.githubusercontent.com/1376607/113633097-60215980-963a-11eb-99aa-7ac45091d6f8.png)
At 100%, the letter _H_ is 77px tall.

![typetura-110](https://user-images.githubusercontent.com/1376607/113633159-74fded00-963a-11eb-8e67-81c763b7d0e7.png)
At 110%, the letter _H_ is 70px tall when it should be ~85px.

![typetura-125](https://user-images.githubusercontent.com/1376607/113633234-8fd06180-963a-11eb-9ee4-92bf058d2465.png)
At 125%, the letter _H_ is 62px tall when it should be ~96px.

![typetura-150](https://user-images.githubusercontent.com/1376607/113633337-c6a67780-963a-11eb-9692-84db0784929d.png)
At 150%, the letter _H_ is 55px tall when it should be ~115px.

![typetura-175](https://user-images.githubusercontent.com/1376607/113633396-e5a50980-963a-11eb-8847-b421961f7923.png)
At 175%, the letter _H_ is 54px tall when it should be ~135px.

![typetura-200](https://user-images.githubusercontent.com/1376607/113633465-053c3200-963b-11eb-8864-df4e09f100c1.png)
At 200%, the letter _H_ is 213px tall when 154px would have been fine. I think this happened because it flipped over to a mobile context as the page reflow suggests.

As you can see, as I zoom the page, the text gets smaller. This is very much the opposite of what a low vision user wants. That the text gets dramatically larger at 200% is good, but also not the case on my client site(s).

I looked through the documentation for any reference to WCAG or this specific issue, ideally with guidance on how to account for it. The only accessibility note I found is on the [_Best Practices_](https://docs.typetura.com/creating-with-typetura/best-practices) page.

> Accessibility tip
> Use percentage units so that a readers default font size is preserved. Normally this is 16px, and 100% would equal 16px.

Without a method, or at least documentation, to address the text sizing issue I am in a position where I have to evaluate whether they can reasonably continue to use Typetura.

Do you have anything in the feature or documentation pipeline to offer guidance on how to remediate or satisfy WCAG SC 1.4.4: Resize Text?

**Comment by scottkellum** [comment] 2021-04-05 23:04
Thanks @aardrian for this detailed write up.

Question about WCAG SC 1.4.4: Resize Text. I am reading it now and do not see this as a failure in my interpretation of it. Yes, the text gets smaller but that is because the more constrained layout has less space. It is still a faithful 200% upscale of a page at a 50% smaller viewport. This behavior is NOT akin to the issues with viewport units which don’t scale up consistently.

I’d love to chat with you more via video call or otherwise to dig into this. I understand our interpretations may be different and I may be missing something. My email is scott@typetura.com

**Comment by scottkellum** [comment] 2021-04-05 23:19
I guess where I am confused is how is this different from a media query at a smaller viewport size getting triggered with a different headline size as a result of page zoom? The text can’t get so big that it doesn’t fit on the screen, that would be illegible to everyone.

**Comment by aardrian** [comment] 2021-04-06 00:47
> I am reading it now and do not see this as a failure in my interpretation of it. Yes, the text gets smaller but that is because the more constrained layout has less space. It is still a faithful 200% upscale of a page at a 50% smaller viewport.

The text gets smaller; it is doing the opposite of what the SC is asking. My viewport size in those screen shots has not changed. It is still 1,920 pixels.

> This behavior is NOT akin to the issues with viewport units which don’t scale up consistently.

You are right that it is not the same. Text sized exclusively with viewport units does not get smaller as the page is zoomed.

> how is this different from a media query at a smaller viewport size getting triggered with a different headline size as a result of page zoom?

It's not. A user who visits any page with or without text size set from a media query must also be able to zoom that default text to 200%.

> The text can’t get so big that it doesn’t fit on the screen, that would be illegible to everyone.

Assuming it cannot wrap, you mean. But it _can_ get that large and that is ok. I have worked with many low vision users who zoom so much that only one or a few letters are visible in the viewport at a time. After 200% zoom they generally do not expect the text to wrap well (or at all for very large zooms).

I appreciate that you want to understand how WCAG applies and that your interpretation of the SC does not correspond with mine, but these yes/no questions might help…

1. If a person visits a page and the text is too small to easily read, and that person uses the browser zoom as a result, do you think they would expect the text to get smaller?

2. If the text gets smaller when zooming the page, do you think that person would find it useful?

3. Do you think that would match their experience across the web?

**Comment by scottkellum** [comment] 2021-04-06 01:43
Ah, I think I see the disconnect here. Typetura scales text relative to the **body** text size and layout. When you zoom in with Typetura, the body text grows proportionally bigger, as intended. Due to layout shifts when scaling, the headlines can at times become proportionally smaller. Typetura keeps the page as legible as possible at any size or page scale factor, and, yes, that sometimes means headlines shrink as the body copy increases in size.

> If a person visits a page and the text is too small to easily read, and that person uses the browser zoom as a result, do you think they would expect the text to get smaller?

In a page zoom, the **body** copy gets bigger, and headlines need to react in such a way that they remain both legible and in proportion to layout shifts in the body text. Since when I zoom in on a page it usually means I'm having trouble reading the smaller text on that page, it's that text that needs to get bigger, not the headline. Since the headline is already the largest text on the page, it doesn't need to grow in size; it needs to remain legible and proportional.

> If the text gets smaller when zooming the page, do you think that person would find it useful?

If the text in the body copy got smaller, no, but if the headline text gets smaller while the body copy gets bigger in order to support legibility, yes, I do think that meets the need of the viewer. 

> Do you think that would match their experience across the web?

Yes

This is akin to a smaller breakpoint being triggered as you zoom into the page and smaller text being rendered like most websites do today. As we know, as the page is zoomed in, a smaller _virtual_ viewport is used. So if the viewport is 1,920px, then the virtual viewport is 960px at a zoom level of 200%. In most design systems, you have  mobile screen typographic scale that's smaller than the desktop, and zooms trigger that mobile breakpoint. In that case, just as in this demo, you would experience the shrinking of headline size while the body copy grows. 

To follow up, I would be excited to consult with your client to get their styles more compliant. Through that consultation, we would make the typographic scale less aggressive on larger screens and change the interpolation easing curve to be more linear.

**Comment by aardrian** [comment] 2021-04-06 14:44
I also think I see the disconnect here. You keep saying "legible", but you have not defined it. I am saying "200%" and I have defined it by reference.

> Typetura keeps the page as legible as possible at any size or page scale factor, and, yes, that sometimes means headlines shrink as the body copy increases in size.

Arguably, making the text smaller as a user zooms is not keeping the page as legible as possible.

> Since when I zoom in on a page it usually means I'm having trouble reading the smaller text on that page, it's that text that needs to get bigger, not the headline. Since the headline is already the largest text on the page, it doesn't need to grow in size; it needs to remain legible and proportional.

The users I work with who zoom want to zoom _all_ the text, including headlines. Some of them are low vision, some of them are just trying to read a thing on their device while in the sun (a lot of working outdoors in the pandemic, it turns out).

Now, to be fair, the sample I linked does let the body copy grow. But the example I am reviewing does not.

> > If the text gets smaller when zooming the page, do you think that person would find it useful?
>
> If the text in the body copy got smaller, no, but if the headline text gets smaller while the body copy gets bigger in order to support legibility, yes, I do think that meets the need of the viewer.

Supporting "legibility" could also include making the headlines bigger. I know users who would not agree it met their needs or was more legible.

> > Do you think that would match their experience across the web?
>
> Yes

I just grabbed a [CNN page](https://www.cnn.com/2021/04/05/us/gonzaga-baylor-march-madness-title-game-trnd/index.html) and that is not what happens. There may be value in grabbing the top n sites and checking.

> This is akin to a smaller breakpoint being triggered as you zoom into the page and smaller text being rendered like most websites do today.

As above, I think the statement "most" needs to be validated. Regardless, even if some sub-set of sites does it, that does not mean they do it correctly or that they would pass this SC.

> As we know, as the page is zoomed in, a smaller virtual viewport is used. So if the viewport is 1,920px, then the virtual viewport is 960px at a zoom level of 200%.

The user's screen has not changed size. The visual angle of things on the screen has not changed size (they take up the same area in the user's visual field). The viewport is still 1,920px, no matter the virtual viewport. While the responsive reflow is good overall (and helps satisfy [1.4.10 Reflow](https://www.w3.org/WAI/WCAG21/quickref/#reflow)), it does not make it ok to disallow resizing content. The user still needs the _thing_ to be bigger when they zoom.

> To follow up, I would be excited to consult with your client to get their styles more compliant. Through that consultation, we would make the typographic scale less aggressive on larger screens and change the interpolation easing curve to be more linear.

I appreciate the offer, but for the specific scenario in front of me today WCAG compliance is the goal. Budget (time and effort) is a factor. Since today they cannot meet SC 1.4.4, there is no documentation to walk them through how the library addresses that SC, and there is no other guidance on remediation, I can only give a use / do not use recommendation.

I am happy to continue this thread because I suspect if I am seeing this happen, then others are as well and they will also want guidance (other than tearing it out and going back to traditional type sizing).

**Comment by scottkellum** [comment] 2021-04-06 15:27
Thanks again @aardrian. I’m curious what you would like to satisfy this issue as it seems to be inherent to the _design_ and not the technology. As I said I am more than happy to consult on the design with your client, and why I am so frustrated is that the WCAG spec is opposed to the very concept of fluid typography, and even responsive typography.

Here is your website where the headline gets smaller when going from 133% to 150% at a viewport width of 1270. While yes, this is a more subtle symptom, it is a result of the exact same underlying cause. And this is why I diagnose this as a design problem, not a problem with the tech and am struggling to figure out how to help you with this issue.

<img width="1353" alt="Screen Shot 2021-04-06 at 8 12 05 AM" src="https://user-images.githubusercontent.com/377189/113736158-b8e00900-96b1-11eb-980c-deac6dce2cc4.png">
<img width="1353" alt="Screen Shot 2021-04-06 at 8 12 16 AM" src="https://user-images.githubusercontent.com/377189/113736164-b9789f80-96b1-11eb-9dd0-d55e73a1ac8b.png">

**Comment by scottkellum** [comment] 2021-04-06 15:49
> Now, to be fair, the sample I linked does let the body copy grow. But the example I am reviewing does not.

Happy to consult with your client on this. This is a design problem and should be a relatively easy fix. I hope your client is also using relative units throughout their typographic system as, I’m sure you are well aware, user font size preference is also extremely important to inherit. Headlines should _never_ get smaller than the body copy, but some variability is important to keep them legible as layout and scale changes, and yes, sometimes this means making them smaller.

**Comment by aardrian** [comment] 2021-04-06 16:32
I appreciate that you are calling out my site because it also demonstrates the issue. It is on my list, but I have not yet fixed it yet (it also has alignment issues at very wide viewports, and I waffle over the outline technique). The reason I have made it a lower priority is two-fold:
1. The rest of the text scales;
2. The headlines start at 600% of the body copy (which is 130% of the browser default), dropping to 500% at narrow viewports.

So yes, the headlines on my site fail 1.4.4. I am also not packaging up my code for others to use.

> As I said I am more than happy to consult on the design with your client, and why I am so frustrated is that the WCAG spec is opposed to the very concept of fluid typography, and even responsive typography.

I am not sure explaining your frustrations to the client will help.

WCAG is not opposed to fluid/responsive typography. Two SCs (1.4.4 and 1.4.10) actively promote responsive typography.

Perhaps the feedback you are giving me about relative units, along with how to address 1.4.4 in an implementation, or language a client can use to call out headlines specifically for a VPAT, can be wrapped up as additional documentation on the product site.

**Comment by scottkellum** [comment] 2021-04-06 16:39
> So yes, the headlines on my site fail 1.4.4. I am also not packaging up my code for others to use.

This is a design issue. I’m not trying to call out your website as a gotcha, I’m trying to isolate the issue and help you solve it. I did not write your clients code*. I am using this example to explain that it’s the exact same issue and for the exact same reasons. If you can figure out how to solve this problem on your website, then you can help your client solve the issues with their design.

*unless they are using one of our packages in which case they will get free support for this issue, but as you describe it I doubt it.

**Comment by scottkellum** [comment] 2021-04-06 16:45
As it stands now, I plan on closing this issue out by end of day. As described so far in this thread, it is a design issue, it’s not inherently an issue with the Typetura library.

**Comment by scottkellum** [comment] 2021-04-06 16:52
To repeat what I stated earlier in the thread that might help your client without seeing their implementation or design, this is the general advice I would give:

> make the typographic scale less aggressive on larger screens and change the interpolation easing curve to be more linear

**Comment by scottkellum** [comment] 2021-04-06 19:14
Just to reference another point earlier about expected behavior, yes the CNN page headlines also scale down at a point. This is why I expect this behavior and am not surprised by it. Just about every website adjusts headlines like this. The only difference between these examples and what Typetura is doing is that Typetura interpolates this scaling down across a wider range of zoom levels instead of a specific breakpoint. I don’t see anything wrong with scaling headlines down slightly in these instances, as the rest of the text gets consistently larger, but if you did, my answer on a solve is the same. This is a design problem you can solve by more gradually sizing your text and including a less aggressive easing curve.

<img width="1433" alt="Screen Shot 2021-04-06 at 12 06 29 PM" src="https://user-images.githubusercontent.com/377189/113765024-98737700-96d0-11eb-8a12-20b81df6dbc7.png">
<img width="1433" alt="Screen Shot 2021-04-06 at 12 06 33 PM" src="https://user-images.githubusercontent.com/377189/113765012-94475980-96d0-11eb-927d-e01da42101f7.png">

**Comment by aardrian** [comment] 2021-04-06 19:16
> As it stands now, I plan on closing this issue out by end of day.

That's fine. I assume that also means you will not go with the three suggestions I made or any others you might have thought of from this discussion.

> As described so far in this thread, it is a design issue, it’s not inherently an issue with the Typetura library.

It's a WCAG issue. It is a WCAG issue caused by any code (driven by design requirements, sure) that limits how large text can be zoomed. So no, it is not specific to Typetura, but as I noted when I opened this issue I was looking for dev-facing guidance on how to implement Typetura while also meeting WCAG.

> more than happy to have a call with you or your client to see how we can work this out.

As I am not doing remediation (yet?), my role right now is strictly the WCAG compliance review (think VPAT). I have passed this along so they can engage you directly should they choose to remediate while keeping the library. To recap:

> Do you have anything in the feature or documentation pipeline to offer guidance on how to remediate or satisfy WCAG SC 1.4.4: Resize Text?

My takeaway here is that the answer is no.

**Comment by scottkellum** [comment] 2021-04-06 19:33
Thank you @aardrian, I will contemplate documentation regarding this. Do you know of any other documentation regarding WCAG SC 1.4.4: Resize Text as it is such a common issue across the web? Seems like maybe there should be something in MDN docs around media queries but I’m not finding much.

There will be no code changes as a result of this thread as I don’t see any issues raised here that are a result of the codebase. I have looked into scaling up specifically based on zoom level as a result of you raising this issue but that would be counter-intuitive to the way all other web tooling works, which is why you are seeing this with media query driven websites.

**Comment by aardrian** [comment] 2021-04-06 19:57
The WCAG SC I linked has technique documents, which are probably the best starting point as they inform remediation and pass/fail evaluations. MDN is community driven so if nobody has taken their time to write it, it would not be there.

**Comment by scottkellum** [comment] 2021-04-06 20:04
Thanks again, I will contemplate this and what to do with this information. It is quite difficult to be the first maintainer to write this documentation so I will need to assess where and how to effectively do this. Also it seems like something far more general of an issue than something Typetura specific so I am contemplating where to put this information.

**Closed** 2021-04-07 20:19 UTC
Labels: Accessibility
